version: '3.8'

services:
  postgres:
    container_name: postgres-app
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tms-network

  app:
    container_name: task-management-service
    image: task-management-service:latest
    restart: no
    environment:
      SPRING_PROFILE: dev
      PORT: 8080
      TZ: GMT+9
      DB_PASSWORD: root
      DB_USERNAME: root
      DB_URL: jdbc:postgresql://postgres:5432/tms
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - tms-network
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      SWAGGER_JSON_URL: /swagger.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./api_document/swagger.yaml:/usr/share/nginx/html/swagger.yaml

volumes:
  postgres_data:

networks:
  tms-network:
    driver: bridge
