spring:
  application:
    name: task-management-service
  jackson:
    time-zone: ${TZ}
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT}
