openapi: 3.0.3
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing users and tasks (bugs & features)

servers:
  - url: http://localhost:8080

tags:
  - name: User
    description: Operations related to users
  - name: Task
    description: Operations related to tasks

paths:
  /api/v1/users:
    post:
      tags: [User]
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [username, fullName]
              type: object
              properties:
                username:
                  type: string
                fullName:
                  type: string
      responses:
        '201':
          description: User created
    get:
      tags: [User]
      summary: Get all users
      responses:
        '200':
          description: A list of users

  /api/v1/users/{id}:
    get:
      tags: [User]
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User found
    put:
      tags: [User]
      summary: Update user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [fullName]
              type: object
              properties:
                fullName:
                  type: string
      responses:
        '204':
          description: User updated
    delete:
      tags: [User]
      summary: Delete user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted

  /api/v1/tasks:
    post:
      tags: [Task]
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, userId]
              properties:
                name:
                  type: string
                userId:
                  type: integer
                bug:
                  type: object
                  properties:
                    severity:
                      type: integer
                    stepsToReproduce:
                      type: string
                feature:
                  type: object
                  properties:
                    businessValue:
                      type: string
                    deadline:
                      type: string
                      format: date
      responses:
        '201':
          description: Task created
    get:
      tags: [Task]
      summary: Get all tasks or search by filter
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
        - name: userId
          in: query
          required: false
          schema:
            type: integer
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of tasks

  /api/v1/tasks/{id}:
    get:
      tags: [Task]
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task found
    put:
      tags: [Task]
      summary: Update task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [name, userId, status]
              type: object
              properties:
                name:
                  type: string
                status:
                  type: string
                userId:
                  type: integer
                bug:
                  type: object
                  properties:
                    severity:
                      type: integer
                    stepsToReproduce:
                      type: string
                feature:
                  type: object
                  properties:
                    businessValue:
                      type: string
                    deadline:
                      type: string
                      format: date
      responses:
        '204':
          description: Task updated
    delete:
      tags: [Task]
      summary: Delete task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        fullName:
          type: string

    Task:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
        userId:
          type: integer
        bug:
          $ref: '#/components/schemas/Bug'
        feature:
          $ref: '#/components/schemas/Feature'

    Bug:
      type: object
      properties:
        severity:
          type: integer
        stepsToReproduce:
          type: string

    Feature:
      type: object
      properties:
        businessValue:
          type: string
        deadline:
          type: string
          format: date
