### U0001 - Create user
POST http://localhost:8080/api/v1/users
Accept: application/json
Content-Type: application/json

{
  "username": "user2",
  "fullName": "User2"
}


### U0002 - Get users
GET http://localhost:8080/api/v1/users
Accept: application/json
Content-Type: application/json


### U0003 - Get user
GET http://localhost:8080/api/v1/users/1
Accept: application/json
Content-Type: application/json


### U0004 - Update user
PUT http://localhost:8080/api/v1/users/1
Accept: application/json
Content-Type: application/json

{
  "fullName": "User"
}


### U0005 - Delete user
DELETE http://localhost:8080/api/v1/users/3
Accept: application/json
Content-Type: application/json
